language: go

sudo: false

go:
  - "1.11.x"

env:
  - GO111MODULE=on

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go install -v -mod=vendor ./...

script:
  - go vet ./...
  - go test -v -race -covermode=atomic -coverprofile=coverage.out -tags=integration ./...
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
